--- #YAML:1.0
name:                DNS-ZoneEdit
version:             0.03
abstract:            Update your ZoneEdit dynamic DNS records
license:             perl
author:              
    - Evan Giles <egiles@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    HTTP::Request::Common:         1.19
    LWP::UserAgent:                2.001
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
