--- #YAML:1.0
name:               DNS-ZoneEdit
version:            1
abstract:           Update your ZoneEdit dynamic DNS records
author:
    - Evan Giles <egiles@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    LWP::UserAgent:  2.001
resources:
    repository:  git://github.com/egiles/dns-zoneedit.git
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
